### ISSUE TITLE
Changing the Pretrained model with a multingual model

### ISSUE THREAD

**Issue by JohnPFL** [yumeng5/LOTClass#1]
hello @yumeng5.  
First of all, all my compliments to you and your team for the great results with this model. 
I want to test it a lot, but to use it I need to change the pretrained model with a multingual one (Italian language problem). 
I changed this part from model.py: 

```
`from transformers import AutoTokenizer, AutoModelForMaskedLM
from transformers.modeling_bert import BertOnlyMLMHead
from torch import nn
import sys
class LOTClassModel(AutoModelForMaskedLM):
    tokenizer = AutoTokenizer.from_pretrained("dbmdz/bert-base-italian-cased")
    model = AutoModelForMaskedLM.from_pretrained("dbmdz/bert-base-italian-cased")

```
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.bert = model(config, add_pooling_layer=False)
        self.cls = BertOnlyMLMHead(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)
        self.activation = nn.Tanh()
        self.classifier = nn.Linear(config.hidden_size, config.num_labels)
        self.init_weights()
        # MLM head is not trained
        for param in self.cls.parameters():
            param.requires_grad = False`

Then I changed this part of trainer.py:
`        self.pretrained_lm = 'dbmdz/bert-base-italian-cased'
        self.tokenizer = AutoTokenizer.from_pretrained(self.pretrained_lm)
        self.vocab = self.tokenizer.get_vocab()
        self.vocab_size = len(self.vocab)
        self.mask_id = self.vocab[self.tokeniz`

And I get the error: 

```
`Epoch 1:
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    main()
  File "train.py", line 57, in main
    trainer.mcp(top_pred_num=args.top_pred_num, match_threshold=args.match_threshold, epochs=args.mcp_epochs)
  File "/comments_class/code/lotclass/src/trainer.py", line 454, in mcp
    mp.spawn(self.mcp_dist, nprocs=self.world_size, args=(epochs, loader_name))
  File "/my_env/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/my_env/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/my_env/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "//my_env/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/comments_class/code/lotclass/src/trainer.py", line 423, in mcp_dist
    attention_mask=input_mask)
  File "/my_env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "//my_env/lib64/python3.6/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "//my_env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/my_env/lib64/python3.6/site-packages/transformers/modeling_bert.py", line 1149, in forward
    assert kwargs == {}, f"Unexpected keyword arguments: {list(kwargs.keys())}."
AssertionError: Unexpected keyword arguments: ['pred_mode'].`
```

What am I doing wrong? 
Thanks again.

**Comment by yumeng5** [comment]
Hi @JohnPFL,

Thanks for your interest in our work. If you are still using BERT as the language model, I believe you don't need to change anything in `model.py`; just change [line 40 of `trainer.py`](https://github.com/yumeng5/LOTClass/blob/e3c93ee5fa2af7952143abaec24d5f683720e38d/src/trainer.py#L40) to include your Italian BERT model (i.e., `self.pretrained_lm = 'dbmdz/bert-base-italian-cased'`). You also won't need to change the tokenizer part--it automatically uses your loaded language model's tokenizer.

Let me know if you still encounter any problems.

Best,
Yu

**Comment by JohnPFL** [comment]
Hi @yumeng5! 
Thanks a lot for the response. The model was perfectly trained. When trying to predict new files, when: 
`model= LOTClassModel.from_pretrained(final_model)`
it gives me the subsequent error: 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte`
This is probably a very stupid error.
Sorry and thanks again for your work.

**Comment by yumeng5** [comment]
Hi @JohnPFL,

I don't think the final model can be loaded via the `from_pretrained` function, which is specifically for loading pre-trained language models (not fine-tuned ones). To apply the trained LOTClass model to test sets, you could refer to the [`write_results` function](https://github.com/yumeng5/LOTClass/blob/e3c93ee5fa2af7952143abaec24d5f683720e38d/src/trainer.py#L618-L631) where the final model is loaded via `load_state_dict`.

Actually, you won't need to change any code to apply the final model to new data--you can just pass the new corpus file path as the command line argument `--test_file` and rerun the code. As long as your intermediate checkpoints (the `.pt` files) are still there, the final model will be directly applied to your new corpus (without re-training).

Thanks,
Yu

**Comment by JohnPFL** [comment]
It all worked perfectly! 
Thanks again and all my compliments to the team!
