### ISSUE TITLE
RuntimeError: No rendezvous handler for tcp://

### ISSUE THREAD

**Issue by JeremySun1224** [yumeng5/LOTClass#2]
Hi @yumeng5 😊

Exciting work. 👍I'm trying to run the agnews.sh script you gave. And get the error below. I only have one GPU. Is this the error caused by this?

## Environment info

     
- transformers version: 3.4.0
- Platform: windows10
- Python version:3.6.9
- PyTorch version (GPU?): 1.7
- GPU: 1080ti * 1
- Using distributed or parallel set-up in script?: yes

## agnews.sh
"""
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export CUDA_VISIBLE_DEVICES=0

DATASET=agnews
LABEL_NAME_FILE=label_names.txt
TRAIN_CORPUS=train.txt
TEST_CORPUS=test.txt
TEST_LABEL=test_labels.txt
MAX_LEN=200
TRAIN_BATCH=32
ACCUM_STEP=4
EVAL_BATCH=128
GPUS=1
MCP_EPOCH=3
SELF_TRAIN_EPOCH=1
......
"""

## Problem
"""
Administrator@it-202007061711 MINGW64 /e/PycharmProjects/CCF/reference/LOTClass-master
$ sh agnews.sh
Namespace(accum_steps=4, category_vocab_size=100, dataset_dir='datasets/agnews/', dist_port=12345, early_stop=False, eval_batch_size=128, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max_l
en=200, mcp_epochs=3, out_file='out.txt', self_train_epochs=1.0, test_file='test.txt', test_label_file='test_labels.txt', top_pred_num=50, train_batch_size=32, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Label names used for each class are: {0: ['politics'], 1: ['sports'], 2: ['business'], 3: ['technology']}
Some weights of the model checkpoint at bert-base-uncased were not used when initializing LOTClassModel: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing LOTClassModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LOTClassModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LOTClassModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias', 'dense.weight', 'dense.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading encoded texts from datasets/agnews/train.pt
Loading texts with label names from datasets/agnews/label_name_data.pt
Loading encoded texts from datasets/agnews/test.pt
Contructing category vocabulary.
Traceback (most recent call last):
  File "src/train.py", line 69, in <module>
    main()
  File "src/train.py", line 56, in main
    trainer.category_vocabulary(top_pred_num=args.top_pred_num, category_vocab_size=args.category_vocab_size)
  File "E:\PycharmProjects\CCF\reference\LOTClass-master\src\trainer.py", line 296, in category_vocabulary
    mp.spawn(self.category_vocabulary_dist, nprocs=self.world_size, args=(top_pred_num, loader_name))
  File "D:\Anaconda3\envs\BertWWMExt\lib\site-packages\torch\multiprocessing\spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Anaconda3\envs\BertWWMExt\lib\site-packages\torch\multiprocessing\spawn.py", line 157, in start_processes
    while not context.join():
  File "D:\Anaconda3\envs\BertWWMExt\lib\site-packages\torch\multiprocessing\spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\BertWWMExt\lib\site-packages\torch\multiprocessing\spawn.py", line 19, in _wrap
    fn(i, *args)
  File "E:\PycharmProjects\CCF\reference\LOTClass-master\src\trainer.py", line 260, in category_vocabulary_dist
    model = self.set_up_dist(rank)
  File "E:\PycharmProjects\CCF\reference\LOTClass-master\src\trainer.py", line 67, in set_up_dist
    rank=rank
  File "D:\Anaconda3\envs\BertWWMExt\lib\site-packages\torch\distributed\distributed_c10d.py", line 421, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "D:\Anaconda3\envs\BertWWMExt\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
**RuntimeError: No rendezvous handler for tcp://**
"""
Looking forward to your reply, thankyou.

**Comment by JeremySun1224** [comment]
PyTorch needs to be updated to version 1.7 on windows systems to support distributed computing.

**Comment by yumeng5** [comment]
Hi @JeremySun1224,

Thanks for your interest in our work and sorry for the delay in my response--I've been quite busy recently. Not sure if you have already resolved the issue; I believe it's more or less related to the platform--I only tested the code on Linux systems and never tested it on Windows. It seems from [here](https://discuss.pytorch.org/t/pytorch-windows-is-parallelization-over-multiple-gpus-now-possible/59971/3) that the PyTorch distributed training lacks full support for the Windows system. However, since you are running the code on a single GPU, you don't really need the parallel training part. Specifically, I believe you only need to change everywhere that calls `set_up_dist` (like [this line](https://github.com/yumeng5/LOTClass/blob/40f5ce17468766e55f987b206ca8234540a745fc/src/trainer.py#L259)) to `model = self.model.to(0)`, and the [`DistributedSampler`](https://github.com/yumeng5/LOTClass/blob/40f5ce17468766e55f987b206ca8234540a745fc/src/trainer.py#L226) to [`RandomSampler`](https://pytorch.org/docs/stable/data.html?highlight=randomsampler#torch.utils.data.RandomSampler).

I hope this helps! Let me know if you still encounter any problems.

Thanks,
Yu

**Comment by JeremySun1224** [comment]
Hi @yumeng5 ,
Following your method, the program has been running smoothly on my Windows 10 computer, and words cannot express my gratitude. You're awesome👍👍👍, worship face.😊

Thank you again.🌹

**Comment by yumeng5** [comment]
Hi @JeremySun1224,

I forgot to mention that you need to change this part too--`dist.all_gather` is called whenever we want to gather tensors across multiple GPUs (e.g. for computing loss and test accuracy). If you are not using distributed training, then this part should be removed. Specifically, [line 435](https://github.com/yumeng5/LOTClass/blob/aa65ae2d249605adc28ad9650fdb867447b48375/src/trainer.py#L435) should be deleted because we don't need to gather the training loss tensor. Similarly, other `dist.all_gather` function calls should be removed as well.

Let me know if you still encounter other issues.

Thanks,
Yu

**Comment by JeremySun1224** [comment]
Hello, I followed your instructions and made changes in all the appropriate places in the code, now the masked category prediction works and the loss is down. But a new error has been generated `torch.nn.modules.module.ModuleAttributeError: 'LOTClassModel' object has no attribute 'module'`. I'm sorry to bother you with this again.
```
Preparing self supervision for masked category prediction.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 938/938 [15:38<00:00,  1.00s/it]
Number of documents with category indicative terms found for each category is: {0: 173, 1: 1331, 2: 1426, 3: 2049}
There are totally 4979 documents with category indicative terms.

Training model via masked category prediction.
Epoch 1:
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [01:23<00:00,  1.87it/s]
Average training loss: 0.8626943826675415
Epoch 2:
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [01:20<00:00,  1.93it/s]
Average training loss: 0.25609952211380005
Epoch 3:
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [01:20<00:00,  1.93it/s]
Average training loss: 0.1329887956380844
Traceback (most recent call last):
  File "src/train.py", line 67, in <module>
    main()
  File "src/train.py", line 58, in main
    trainer.mcp(top_pred_num=args.top_pred_num, match_threshold=args.match_threshold, epochs=args.mcp_epochs)
  File "E:\PycharmProjects\CCF\reference\LOTClass\src\trainer.py", line 469, in mcp
    mp.spawn(self.mcp_dist, nprocs=self.world_size, args=(epochs, loader_name))
  File "D:\Anaconda3\envs\MixText\lib\site-packages\torch\multiprocessing\spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Anaconda3\envs\MixText\lib\site-packages\torch\multiprocessing\spawn.py", line 157, in start_processes
    while not context.join():
  File "D:\Anaconda3\envs\MixText\lib\site-packages\torch\multiprocessing\spawn.py", line 118, in join
    raise Exception(msg)
Exception:
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\MixText\lib\site-packages\torch\multiprocessing\spawn.py", line 19, in _wrap
    fn(i, *args)
  File "E:\PycharmProjects\CCF\reference\LOTClass\src\trainer.py", line 457, in mcp_dist
    torch.save(model.module.state_dict(), loader_file)
  File "D:\Anaconda3\envs\MixText\lib\site-packages\torch\nn\modules\module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'LOTClassModel' object has no attribute 'module'
```
and line 457 is:
`torch.save(model.module.state_dict(), loader_file)`
in your code is [Line441](https://github.com/yumeng5/LOTClass/blob/aa65ae2d249605adc28ad9650fdb867447b48375/src/trainer.py#L441)

Thank you again.🌹

**Comment by yumeng5** [comment]
Hi @JeremySun1224,

You can simply remove the `.module` part (i.e. `torch.save(model.state_dict(), loader_file)`)--`.module` is only used when the model is a parallel-trained one.

Best,
Yu

**Comment by JeremySun1224** [comment]
Hi @yumeng5 The code now runs smoothly on the Windows platform.😊 Thank you very much for your inner advice.🌹
