### ISSUE TITLE
Can this method be used in the scenario of multi-label text classification?

### ISSUE THREAD

**Issue by ScottishFold007** [yumeng5/LOTClass#20]
Hello, can this method be extended to multi-label text classification scenarios?

**Comment by yumeng5** [comment]
Hi @ScottishFold007 

The method may require some nontrivial changes to be applied to multi-label classification tasks. The most challenging part to adapt will be the self-training stage. The current self-training algorithm computes the target distribution by assuming that the document assignment is exclusive to only one label and enhancing the high-confident predictions. I would expect some different designs over there to adapt the method to multi-label classification.

Thanks,
Yu
