### ISSUE TITLE
AssertionError: "时" used as the label name by multiple classes!

### ISSUE THREAD

**Issue by JeremySun1224** [yumeng5/LOTClass#3]
Hi @yumeng5 

I am trying to use your model on Chinese unsupervised text classification corpus. Due to the particularity of Chinese, I follow your method in the README and separate the label names with spaces, but 5: ['时','尚'], 6: ['时','政'] For these two types of repeated words, the following error was reported? How can I adjust to the Chinese data?（我正在中文无监督文本分类语料上尝试使用您的模型，由于中文的特殊性，我按照您在README中的方法，将标签名用空格分开，但是5: ['时', '尚'], 6: ['时', '政']对于这两个类中由于有重重复的字，报了如下的错？请问该怎么调整以适应中文数据呢？）

我的label_name如下：
"""
财 经
房 产
家 居
教 育
科 技
时 尚
时 政
游 戏
娱 乐
体 育
"""

"""
2020-11-20 07:15:48.082470: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Namespace(accum_steps=4, category_vocab_size=100, dataset_dir='datasets/lotclass/', dist_port=12345, early_stop=False, eval_batch_size=128, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max_len=512, mcp_epochs=3, out_file='out.txt', self_train_epochs=1.0, test_file='test.txt', test_label_file=None, top_pred_num=50, train_batch_size=32, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Downloading: 100% 110k/110k [00:00<00:00, 588kB/s] 
Downloading: 100% 2.00/2.00 [00:00<00:00, 1.69kB/s]
Downloading: 100% 112/112 [00:00<00:00, 100kB/s]
Downloading: 100% 19.0/19.0 [00:00<00:00, 17.4kB/s]
Label names used for each class are: {0: ['财', '经'], 1: ['房', '产'], 2: ['家', '居'], 3: ['教', '育'], 4: ['科', '技'], 5: ['时', '尚'], 6: ['时', '政'], 7: ['游', '戏'], 8: ['娱', '乐'], 9: ['体', '育']}
Traceback (most recent call last):
  File "src/train.py", line 67, in <module>
    main()
  File "src/train.py", line 54, in main
    trainer = LOTClassTrainer(args)
  File "/content/drive/My Drive/CCF/reference/LOTClass-master/src/trainer.py", line 50, in __init__
    self.read_label_names(args.dataset_dir, args.label_names_file)
  File "/content/drive/My Drive/CCF/reference/LOTClass-master/src/trainer.py", line 218, in read_label_names
    assert word not in self.label2class, f"\"{word}\" used as the label name by multiple classes!"
AssertionError: "时" used as the label name by multiple classes!
"""

Thank you.

**Comment by yumeng5** [comment]
Hi @JeremySun1224,

Thanks for the question. As you mentioned, many concepts/entities cannot be expressed with a single word in Chinese (e.g. "technology" in Chinese becomes a two-word phrase "科技"). In this case, it doesn't make sense to split a two-word label name into two separate words as they will be treated as independent words and lose the original meaning. Therefore, it might require some extra designs to adapt the current model to Chinese NLP. Specifically, in the label name replacement step, multi-word phrases should be treated as a whole, and the category vocabulary should also contain multi-word phrases instead of only single tokens, thus requiring additional Chinese word segmentation steps. The subsequent steps (Masked Category Prediction & Self-Training) could be kept the same.

Thanks,
Yu

**Comment by JeremySun1224** [comment]
Hi @yumeng5 ，I'm thrilled and so happy to receive your response!🌹 Your reply enlightened me. I might be able to address this issue in two ways：

1. I need to try word-level pretrained LM on the basis of the existing character-level Chinese pretrained LM;
2. I need to modify the tokenize method in transformers.BertTokenizer to retain the Chinese word segmentation results.

Is it feasible for me to do this? 

Thank you so much.❤

(Pardon my broken English.😁)

**Comment by JeremySun1224** [comment]
Hi @yumeng5 
Based on your suggestion, I tried to reproduce your quite meaningful work on the Chinese corpus, the `Contructing category vocabulary` with the following results.
```
$ sh ccfclass.sh
Namespace(accum_steps=64, category_vocab_size=100, dataset_dir='datasets/ccfclass/', dist_port=12345, early_stop=False, eval_batch_size=32, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max
_len=128, mcp_epochs=3, out_file='out.txt', self_train_epochs=1.0, test_file='test.txt', test_label_file=None, top_pred_num=50, train_batch_size=2, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Label names used for each class are: {0: ['财经'], 1: ['房产'], 2: ['家居'], 3: ['教育'], 4: ['科技'], 5: ['时尚'], 6: ['时政'], 7: ['游戏'], 8: ['娱乐'], 9: ['体育']}
Some weights of the model checkpoint at E:\PycharmProjects\CCF\pretrained_model\wobert_base were not used when initializing LOTClassModel: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_rel
ationship.bias']
- This IS expected if you are initializing LOTClassModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing LOTClassModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LOTClassModel were not initialized from the model checkpoint at E:\PycharmProjects\CCF\pretrained_model\wobert_base and are newly initialized: ['dense.weight', 'dense.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading encoded texts from datasets/ccfclass/train.pt
Loading texts with label names from datasets/ccfclass/label_name_data.pt
Loading encoded texts from datasets/ccfclass/test.pt
Contructing category vocabulary.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 267/267 [02:24<00:00,  1.85it/s]
Class 0 category vocabulary: ['财经', '经济', '经管', '财富', '财务', '易经', '财税', '经费', '经济学家', '理财', '经济学', '经贸', '国民经济', '财力', '经商', '月经', '经历', '一经', '经营', '历经', '财年', '财团', '钱财', '商品经济', '
经济社会', '财政部', '经文', '经纪人', '经理', '财物', '人民日报', '未经', '政治经济', '金融', '经由', '东经', '经理人', '发财', '神经', '圣经', '经销商', '中南财经政法大学', '经济体制', '经脉', '资财', '市场经济', '人民网', '经书', '几
经', '新浪', '经营者', '外经贸', '经济带', '财政经济委员会', '经验', '取经', '政治经济学', '佛经', '真经', '证券报', '经济型', '新闻', '外汇', '新华社', '经济林', '新闻网', '中新网', '新华网', '正经', '国内', '内参', '总经理', '北京', '
证券', '资本', '经济效益', '军事', '人民币', '摘要', '记者']

Class 1 category vocabulary: ['房产', '房地产', '房屋', '住房', '地产', '房子', '资产', '购房', '商品房', '产权', '房价', '新房', '楼房', '产能', '产出', '产区', '厂房', '买房', '物产', '房间', '产量', '书房', '出产', '生产', '产物', '产
地', '再生产', '牢房', '产值', '房舍', '住宅', '遗产', '房中', '高产', '第三产业', '固定资产', '药房', '国产', '房门', '子房', '特产', '家产', '破产', '矿产', '投产', '客房', '停产', '住所', '上房', '物业', '乳房', '房县', '开发商', '厨
房', '产于', '生产力', '知识产权', '房里', '产业化', '产业园', '产妇', '产业资本', '第二产业', '水产', '海产', '年产', '年产量', '商品生产', '所有权', '中产阶级', 'house', '盛产', '房基', '生产者', '总产量', '项目', '销售', '病房', '土特
产', '生产量', '开发', '生产资料', '社区', '地段', '小区', '生产方式', '原产', '住处', '农产品']

Class 2 category vocabulary: []

Class 3 category vocabulary: ['教育', '教学', '教师', '教育局', '义务教育', '教导', '教材', '初等教育', '教育厅', '教养', '文教', '特殊教育', '教务', '教室', '学校', '生育', '佛教', '教训', 'education', '教授', '高校', '教派', '婚育', '
教员', '教练', '教官', '宗教', '教书', '道教', '高等学校', '教会', '培训', '教堂', '领教', '教义', '任教', '中小学', '管教', '培养', '学习', '执教', '教法', '基督教', '计划生育', '教徒', '高考', '办学', '校长', '高等院校', '教诲', '新教'
, '院校', '养老', '我校', '校园', '印度教', '教头', '民办教师', '大学', '政治', '行政', '高中', '建设', '事业', '师资', '学生', '知识', '课程', '考试']

Class 4 category vocabulary: ['科技', '科学', '科普', '科学技术', '科研', '高新技术', '思科', '科技园区', '信息技术', '科隆', '学科', '技能', '本科', '文科', '百科', '外科', '科学家', '自然科学', '专科', '特技', '理科', '科目', '创新', '
技工', '技艺', '技术性', '科比', '社会科学', '科长', '技巧', '华中科技大学', '科威特', '妇科', '科举', '技改', '智能', '绝技', '中科院', '莫斯科', '技术开发区', '环保', '研发', '科学院', '亚科', '高端', '企业', '杂技', '该科', '高新', '
智慧', '科教兴市', '技法', '未来', '物质', '公司', '城市', '创业', '品牌', '中国科学院', '本科生', '精神', '高新区', '可可', 'tech', '股份', '百科全书', '新世纪', '科林斯', '绿色', '全新']

Class 5 category vocabulary: ['时尚', '风尚', '时髦', '时装', '时代', '潮流', '高尚', '崇尚', '和尚', '时间', '尚未', '时空', 'fashion', '时光', '设计', '尚无', '时刻', '即时', '尚有', '过时', '设计师', '实时', '时时', '随时', '尚可', '
流行', '奢华', '时报', '风格', '精致', '大衣', '适时', '现时', '服装', '衣着', '高潮', '时期', '与众不同', '准时', '时而', '时不时', '大气', '换装', '奢侈品', '气质', '思潮', 'vogue', '一时间', '时常', '尚书', '童装', '浪潮', '热潮', '趋
势', '优雅', '多元', '费时', '时机', '高雅', '性感', '造型', '时任', '个性', '上衣', '有时候', '多元化', '华丽', '都市', '低调', '女王', '西装', '高贵', '最新', '典雅', '大牌', '包装', '大众', '元素', '模特']

Class 6 category vocabulary: []

Class 7 category vocabulary: ['游戏', '上游', '游记', '游客', '下游', '游行', '游离', '中游', '出游', '戏曲', '导游', 'lol', '游击', '游人', '漫游', '戏称', '游牧', 'game', '系统', '游动', '角色', 'rpg', '游子', '陆游', '游击队', '过关',
 '游击战', '一款', '策略', '系列', '服务器', 'pc', '游历', '游荡', 'dota', '天堂', '剧情', 'coc', '歌曲', '地图', 'games', '出境游', '数据', '选择', 'play', 'online', 'app', 'wow', '英雄', '春游', '一个', '软件', '世界', 'steam', '唱戏',
 'ga']

Class 8 category vocabulary: ['娱乐', '快乐', '俱乐部', '欢乐', '乐园', '乐趣', '生活', '乐器', '乐观', '玩具', '休闲', 'entertainment', '农家乐', '玩耍', '互动', '乐舞', '商务', '永乐', '享受', '乐于', '消费', '购物', '礼乐', '乐意', '
乐曲', '音乐家', '共享', '欣赏', '影视', '音乐会', '饮食', '休息', '服务', '医疗', '社交', '文艺', '音乐厅', '放松', '电影', '愉悦', '传媒', '乐队', '趣味', '视频', '餐饮', '公共', '交互', '便利', '资讯', '大乐', '美食', '电视', '居住',
'悠闲']

Class 9 category vocabulary: ['体育', '体操', '体能', '体检', '体质', '团体', '体制', '群体', '体格', '体力', '身体', '实体', '体重', '足球', '一体', '总体', '一体化', '个体', '天体', '体表', '字体', '全体', '体系', '山体', '篮球', '形体
', '单体', '人体', '体现', '体裁', '肉体', '体会', '奥运', '集体', '运动会', '晶体', '立体', '运动员', '水体', '网球', '肢体', '车体', '大体', '机体', '遗体', '本体', '载体', 'sports', '政体', '流体', '体内', '奥林匹克', '羽毛球', '健身'
, '液体', '体型', '奥运会', '体温', '体外', '乒乓球', '得体', '比赛', '物体', '体液', '赛事', '主体', '解体', 'nba']

Preparing self supervision for masked category prediction.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1032/1032 [06:10<00:00,  2.79it/s]
Number of documents with category indicative terms found for each category is: {0: 2908, 1: 4600, 2: 0, 3: 2346, 4: 2010, 5: 1801, 6: 0, 7: 1890, 8: 288, 9: 5963}
Traceback (most recent call last):
  File "src/train.py", line 67, in <module>
    main()
  File "src/train.py", line 58, in main
    trainer.mcp(top_pred_num=args.top_pred_num, match_threshold=args.match_threshold, epochs=args.mcp_epochs)
  File "E:\PycharmProjects\CCF\reference\LOTClass\src\trainer.py", line 468, in mcp
    self.prepare_mcp(top_pred_num, match_threshold)
  File "E:\PycharmProjects\CCF\reference\LOTClass\src\trainer.py", line 407, in prepare_mcp
    assert category_doc_num[i] > 10, f"Too few ({category_doc_num[i]}) documents with category indicative terms found for category {i}; " \
AssertionError: Too few (0) documents with category indicative terms found for category 2; try to add more unlabeled documents to the training corpus (recommend) or reduce `--match_threshold` (not recommend)
```
**Strangely, two categories (2: ['家居'] and 6: ['时政']) did not find the category word**, causing the program to break. The corpus of my experiment contains more text for these two categories. What do you think is the reason for this? Do you have any good suggestions? 😊

Sincere thanks.🌹

**Comment by yumeng5** [comment]
Hi @JeremySun1224,

Since I'm not working on Chinese NLP, my knowledge and experience with Chinese pre-trained LMs are limited--I'm providing my suggestions below which might not be the best solution:

1. If there are Chinese pre-trained LMs that use phrase-level vocabulary (i.e., treating "科技", "时政", etc. as integrated tokens) instead of character-level vocabulary, you could directly use those LMs without modifying any code in LOTClass (just load your Chinese pre-trained BERT model).
2. If you have to use character-level Chinese LMs, don't change the tokenization method because it won't work--those phrases that are not recognized by the model during pre-training won't have their token embeddings, and changing the tokenization method won't fix it. Perhaps you could try to first apply a Chinese word segmentation method to extract phrases from the corpus, and then build category vocabulary by examining which phrases (extracted by the word segmentation tool) can replace the label names (i.e. both words of the replacing phrase should appear at the top-50 MLM predictions of the two-word position corresponding to the label name such as "科技"). Then during the MCP step, category-indicative terms should also be located at phrase-level (i.e., check if consecutive tokens' top-50 MLM predictions can form phrases that overlap with the category vocabulary). The self-training step could be kept unchanged.

I hope this helps. Let me know if you have other questions.

Best,
Yu

**Comment by JeremySun1224** [comment]
Hi @yumeng5 Following your instructions, I have successfully reused your model on the Chinese corpus with good results. Words cannot express my gratitude and I wish you all the best.

**Comment by yumeng5** [comment]
Great! Thanks for letting me know. Good luck with your project!
