### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/agnews/label_names.txt'

### ISSUE THREAD

**Issue by horacioHao** [yumeng5/LOTClass#4]
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/agnews/label_names.txt'

**Comment by yumeng5** [comment]
Hi @horacioHao,

Did you download the AGNews data by running [this bash script](https://github.com/yumeng5/LOTClass/blob/master/datasets/agnews/get_data.sh)? The `label_names.txt` file is included in the .zip data file. Alternatively, you can manually download the data file following [this README file](https://github.com/yumeng5/LOTClass/blob/master/datasets/agnews/README.md).

Thanks,
Yu

**Comment by horacioHao** [comment]
> Hi @horacioHao,
> 
> Did you download the AGNews data by running [this bash script](https://github.com/yumeng5/LOTClass/blob/master/datasets/agnews/get_data.sh)? The `label_names.txt` file is included in the .zip data file. Alternatively, you can manually download the data file following [this README file](https://github.com/yumeng5/LOTClass/blob/master/datasets/agnews/README.md).
> 
> Thanks,
> Yu

![image](https://user-images.githubusercontent.com/67046733/101146433-f5451f00-3655-11eb-8f5d-bf2621ee3e1f.png)

**Comment by horacioHao** [comment]
> Hi @horacioHao,
> 
> Did you download the AGNews data by running [this bash script](https://github.com/yumeng5/LOTClass/blob/master/datasets/agnews/get_data.sh)? The `label_names.txt` file is included in the .zip data file. Alternatively, you can manually download the data file following [this README file](https://github.com/yumeng5/LOTClass/blob/master/datasets/agnews/README.md).
> 
> Thanks,
> Yu

![image](https://user-images.githubusercontent.com/67046733/101146480-02620e00-3656-11eb-9881-4ec49c1a8e69.png)
I'm still going to report this error

**Comment by yumeng5** [comment]
Hi @horacioHao, 

Which directory did you run the `agnews.sh` script at? I believe you can avoid the error if you run the script from the root directory of this codebase (i.e., where `agnews.sh` is at). Alternatively, you could change the dataset directory used in the following line to an absolute path (i.e., the full listing of the location of the `datasets` directory in your file system):
https://github.com/yumeng5/LOTClass/blob/aa65ae2d249605adc28ad9650fdb867447b48375/agnews.sh#L18

Thanks,
Yu
