### ISSUE TITLE
is possible to pass muti name for one category

### ISSUE THREAD

**Issue by graceyangfan** [yumeng5/LOTClass#5]
It seems that the model will first find the names in label_names.txt to mask the original text.If the category name has never or rarely been in the train txt,small train materials will be used in the first step,so does it possible to add more words that are smililar to the category name to the label_names.txt.for example instead of post {0:"sports"},just post {0:"competion","players"},asuming that sports has never occured in the train materials

**Comment by yumeng5** [comment]
Hi @graceyangfan,

Thanks for the question. Yes, you can use multiple words as the label name of each category. In fact, there is not a strict definition of which words should be the "label name"--you can choose to use whatever words that can represent the category well and ideally frequently appear in the corpus. As mentioned in the README file, "if multiple words are used as the label name of a category, put them in the same line and separate them with whitespace characters". As an example, you could refer to [DBPedia dataset](https://github.com/yumeng5/LOTClass/tree/master/datasets/dbpedia) where some categories have multiple words as the label name.

Let me know if you have any further questions!

Thanks,
Yu

**Comment by graceyangfan** [comment]
@thanks for your replay, it really help me to understand the ideas in your paper
