### ISSUE TITLE
RuntimeError: The task could not be sent to the workers as it is too large for `send_bytes`.

### ISSUE THREAD

**Issue by jamestch** [yumeng5/LOTClass#8]
**Environment info**
- ubuntu 18.04

- One Tesla V100-16G

- Python3.6.2

- torch 1.5.1

- transformers 3.3.1

**Problem**
When I run ''sh agnews.sh" or 'sh imdb.sh", it works. But when I run "sh amazon.sh" or "sh dbpedia.sh"get the following errors:

Namespace(accum_steps=4, category_vocab_size=100, dataset_dir='datasets/amazon/', dist_port=12345, early_stop=False, eval_batch_size=128, final_model='final_model.pt', gpus=1, label_names_file='label_names.txt', match_threshold=20, max_len=200, mcp_epochs=3, out_file='out.txt', self_train_epochs=0.1, test_file='test.txt', test_label_file='test_labels.txt', top_pred_num=50, train_batch_size=32, train_file='train.txt', update_interval=50)
Effective training batch size: 128
Label names used for each class are: {0: ['bad'], 1: ['good']}
Some weights of the model checkpoint at bert-base-uncased were not used when initializing LOTClassModel: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing LOTClassModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing LOTClassModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LOTClassModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias', 'dense.weight', 'dense.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Reading texts from datasets/amazon/train.txt
Converting texts into tensors.
Saving encoded texts into datasets/amazon/train.pt
Reading texts from datasets/amazon/train.txt
Locating label names in the corpus.
Saving texts with label names into datasets/amazon/label_name_data.pt
Reading texts from datasets/amazon/test.txt
Converting texts into tensors.
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 159, in _feed
    send_bytes(obj_)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
**struct.error: 'i' format requires -2147483648 <= number <= 2147483647**
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/train.py", line 66, in <module>
    main()
  File "src/train.py", line 53, in main
    trainer = LOTClassTrainer(args)
  File "/root/app/LOTClass/src/trainer.py", line 52, in __init__
    self.read_data(args.dataset_dir, args.train_file, args.test_file, args.test_label_file)
  File "/root/app/LOTClass/src/trainer.py", line 201, in read_data
    self.test_data = self.create_dataset(dataset_dir, test_file, test_label_file, "test.pt")
  File "/root/app/LOTClass/src/trainer.py", line 109, in create_dataset
    results = Parallel(n_jobs=self.num_cpus)(delayed(self.encode)(docs=chunk) for chunk in chunks)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/root/anaconda3/envs/py36/lib/python3.6/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/root/anaconda3/envs/py36/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
**RuntimeError: The task could not be sent to the workers as it is too large for `send_bytes`.**

Could you help check it? Thanks a lot!

**Comment by HeimingX** [comment]
I also meet the same problem. Looking forword to be solved.

**Comment by yumeng5** [comment]
Thanks for letting me know the issue. I cannot reproduce the error on my machines but I believe it's related to the joblib parallel package. You could first try to reduce the number of workers by manually setting a smaller `self.num_cpus`:
https://github.com/yumeng5/LOTClass/blob/aa65ae2d249605adc28ad9650fdb867447b48375/src/trainer.py#L32

If it still doesn't work, you could modify the following code piece to remove the joblib part:
https://github.com/yumeng5/LOTClass/blob/aa65ae2d249605adc28ad9650fdb867447b48375/src/trainer.py#L107-L111
Specifically, you could simply replace the code above with
```
input_ids, attention_masks = self.encode(docs)
```
which does not use any parallelization, but it will circumvent the joblib issue.

Let me know if the problem still persists.

Thanks,
Yu

**Comment by HeimingX** [comment]
Hi Yu,

Thanks for the timely solutions. It seems that changing cpu numbers may not work but commenting all joblib part can fix the bug. However, the program runs really slow without the parallelism. so sad~

Cheers,
Haiming
